var questions = ["what website could I not live without?",
"what is the worst high school subject?",
"what's the best song of the last 10 years?",
"if I could win a $1000 gift card for any store, which would it be?",
"what is the best animated movie?",
"what would be the worst thing to burn in a fireplace?",
"what would I not want to have on fire?",
"who is the most overrated band in history?",
"where would be the worst place to wake up?",
"which celeb would make the worst Gandalf from Lord of the Rings?",
"what would I not want to find on my bed after waking up?",
"what's the best thing about being a man?",
"what would I never want to have in my mouth?",
"what is the best reason to quit smoking?",
"what should my gravestone say?",
"what food is definitely not OK to eat after it has fallen on the floor?",
"if I could have a SMALLER anything, what would it be?",
"what would be the best reason to join the Dark Side in Star Wars?",
"what's the best pizza topping?",
"what movie star would I want to be friends with?",
"what would I not want to find in my toilet?",
"what is the best fast food restaurant?",
"what's the best breakfast cereal?",
"what food would be the worst to eat in a crowded movie theatre?",
"if I fell off a balcony, what would I not want to land in?",
"what TV character would I most want to be?",
"if I could have a BIGGER anything, what would it be?",
"who would I not want to sit beside in a crowded movie theatre?",
"which celebrity's house would have the best Halloween candy?",
"what personal quality is the biggest turn off?",
"what city in the world would be the best to live in?",
"what is the best flavor of potato chip?",
"what movie really needs a sequel or another sequel?",
"what would I not want to do on a hot day?",
"what would I do if I finished on the toilet and there was no toilet paper?",
"what is the rudest habit?",
"what is the most disgusting smell?",
"which historical time period would be the most interesting to visit for a day?",
"what super power would be the best to have for a day?",
"what's the best snack food?",
"If I could only have one song I could listen to ever again what would it be?",
"who is the most annoying boy band member or boy musician?",
"what should we learn in high school that we currently don't?",
"If I were a salesperson what would not want to have to sell?",
"where would I never put my hand?",
"what would be the coolest movie prop to own?",
"what's the worst thing about being a man?",
"what's the most important thing in life?",
"if I was in a bathroom stall, what would I not want to hear in the stall beside me?",
"what would I do if I accidentally killed my friend's cat while they were on vacation?",
"what would I never want to have with me in the car on a hot day?",
"if everyone was safe, what would risk going back in my burning house to get?",
"what is the best part of being in high school?",
"what would I say to a person if they accidentally spilled their drink in my lap?",
"what job would I most like to try for a week?",
"if I had to carry a sign around town what would I not want it to say?",
"what famous person should never be allowed to rap?",
"what's the best thing about being a woman?",
"what's the best thing about living in a city?",
"what would I say to my parents if I destroyed the family car?",
"what would be the worst substitute for toilet paper?",
"who's the best rock musician or band?",
"what noise is the most irritating?",
"who's the best looking actor or actress?",
"if an apocalypse happened and it was survival plan time what would I do first?",
"what language would I like to be fluent in?",
"what's my biggest pet peeve?",
"what's the strangest aquatic animal?",
"what really ticks people off?",
"what TV show would it be hardest to live without?",
"what's the most important technology of the past century?",
"what technology do we not have that you wish we did?",
"if I was sitting on the toilet what catastrophic event would I not want to happen?",
"what's the coolest new technology?",
"what would I do if I farted in a crowded elevator?",
"what's the most overrated TV show?",
"what would be the best wedding present?",
"what's the best car?",
"if I could have any sign on my bedroom door, what would it say?",
"which celeb would make the worst presidential candidate?",
"what would I not want the waiter to say to me while bringing the food to the table?",
"what would I want for my next birthday?",
"who's the greatest musician or band of all time?",
"If I could transform into any animal what would it be?",
"what would be the worst part of being a millionaire?",
"what's the most useless household item?",
"what would be the dumbest thing to say in a job interview?",
"what's the best action movie?",
"what is the best excuse to get out of an exam?",
"what television theme song is the most fun to sing with friends?",
"what would I most like to do after I retire?",
"what's the worst thing about being a woman?",
"what would make the worst stuffing for a mattress?",
"if I was going to be executed what would my last meal be?",
"what would you say to someone if they had bad breath?",
"what would be the weirdest thing to find written on a bathroom stall?",
"I just moved in. What's the first thing I do?",
"what is a trait is the most desireable in a boy/man?",
"who's the most underrated actor of all time?",
"if I could choose a nickname to be called what would it be?",
"what superpower would I want to have?",
"what's the most overrated movie of all time?",
"if I had to wipe a country off the map, which would it be?",
"if I could travel back in time one month for one hour then return, what would I do?",
"an alien ship landed on Earth. What should we do?",
"what tv show is the guiltiest pleasure?",
"what is the worst house chore?",
"which celebrity would be it be great to play scrabble against?",
"what is the best flavor of pie?",
"what is the most disgusting sound?",
"what would you not want to see on a restaurant menu?",
"which famous person would I most enjoy playing this game with?",
"what would I do if I peed my pants in class at school?",
"what animal would make the worst mascot for a sports team?",
"which celeb would be the best desert island companion?",
"what's the worst TV show of all time?",
"what would be the worst idea for a pudding flavor?",
"what would I not want to find in a public pool while swimming?",
"what would be the most fun thing to throw off a tall building?",
"what would be the worst place to take a nap?",
"what's the most relaxing vacation spot?",
"what song would make the coolest cell phone ring tone?",
"what song is most likely to pack a dance floor?",
"what food should never be eaten while wearing really expensive clothes?",
"what is the best flavor of chicken wings?",
"who is the coolest video game character of all time?",
"what's the best way to spend a Saturday night?",
"what's the best Olympic sport?",
"what would I scream aloud from the top of a mountain?",
"what's the best band name?",
"what would be the strangest way to answer the phone?",
"what is the best activity to pass the time?",
"if I saw a copy of my next math test in the teacher's garbage, what would I do?",
"what music instrument would I want to be an expert at?",
"what is the best item on the McDonald's menu?",
"what's my favorite hot drink?",
"what certificate would I not want to find on my doctor's office wall?",
"if I had to get a tattoo what would it be?",
"what pet besides a dog or a cat would be the coolest to have?",
"what is a trait is the most desirable in a girl/woman?",
"what would I not want to find in my pocket?",
"where would you not want to fall asleep?",
"what's the best ice cream flavor?",
"what's the most annoying TV commercial?",
"if I could travel to the moon, what would I take to leave behind on its surface?",
"what can you say to your dog that you shouldn't say to your spouse?",
"where would you not want to be bitten by a mosquito?",
"what is the best movie sequel of all time?",
"if I had a big picture of me in the paper, what would I not want the caption to say?",
"what song would I want to be played at my funeral?"];